export const HomeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  darkText: true,
  topLine: "Đăng ký tiêm chủng",
  headline: "Tạo mã QR để đăng kí tiêm chủng",
  description:
    "Những người chưa có căng cước công dân là những người cần tạo mã QR để đăng kí tiêm chủng . Mã QR tiêm chủng chứa các thông tin cá nhân quan trọng , không nên chia sẻ mã của mình cho người khác. ",
  buttonLable: "Bắt đầu ngay",
  imgStart: false,
  img: require("../../images/doctor_01.png"),
  alt: "Car",
  dark: true,
  primary: true,
  btnBg: true,
  btnColor: true,
  dataLink: "/vaccinationRegister",
};

export const HomeObjTow = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  darkText: false,
  topLine: "hướng dẫn khi đi tiêm chủng",
  headline: "Thực hiện quá trình tiêm chủng thông qua việc quét mã QR",
  description:
    "Khi đi tiêm chủng mọi người chỉ cần đem theo căng cước công dân hoặc mã QR được tạo trên Website TC-Covid . Người đi tiêm chủng thực hiện lần lược các bước trong quá trình tiêm chủng theo hướng dẫn của bác sĩ , y tá tại điểm tiêm. ",
  buttonLable: "Tìm hiểu thêm",
  imgStart: true,
  img: require("../../images/doctor_02.jpg"),
  alt: "Car",
  dark: true,
  primary: true,
  btnBg: false,
  btnColor: false,
  dataLink: "",
};

export const HomeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  darkText: false,
  lightTextDesc: false,
  topLine: "Tham gia vào hệ thống tiêm chủng",
  headline: "Điều kiện phải có chứng chỉ hành nghề y tá , bác sĩ ",
  description:
    "Hệ thống chỉ dành cho những người trong hệ thống tiêm chủng . Mọi hành vi giả mạo phải chịu xử lý của pháp luật.",
  buttonLable: "Bắt đầu ngay",
  imgStart: false,
  img: require("../../images/doctor_03.jpg"),
  alt: "Car",
  dark: true,
  primary: true,
  btnBg: false,
  btnColor: false,
  dataLink: "/signup",
};
